### ISSUE TITLE
Game Center plugin linker error with iOS export using Godot 4.3

### ISSUE THREAD

**Issue by RocketRonz** [godotengine/godot-ios-plugins#70]
After upgrading to Godot 4.3.rc2, the iOS export fails when I include the Game Center plugin:
```
Undefined symbols for architecture arm64:
  "Object::get_argument_options(StringName const&, int, List<String, DefaultAllocator>*) const", referenced from:
      vtable for GameCenter in gamecenter-device.debug.a[arm64][3](game_center.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **
```
The same project exports fine with the plugin using Godot 4.2.2

My guess is that I need to checkout the Godot 4.3 submodule before building the libraries but there is no 4.3 branch available in GitHub yet. Is this just a case of waiting until a stable version of 4.3 is released? Thanks for any help.

**Comment by owlnewworlds** [comment]
You can checkout the commit of any release, I'm trying myself to make the Game Center plugin work and I passed through that stage by doing a checkout of the Godot source code 4.3 RC 3.

Now, when I call the authenticate function, it returns a null result and it doesn't work. If by any case, you happen to make a successfull authenticate call, let me know ^^'

**Comment by RocketRonz** [comment]
The easiest solution for me was to revert my Godot project and code back to the latest stable version (4.2.2) as I need to focus my efforts on creating a game. The plugin might still need some work to support 4.3 as it is still a preview build, seems to work fine with 4.2.2 though.

**Comment by RocketRonz** [comment]
Ok, so uploading a 4.2.2 build to TestFlight doesn't work (ITMS-90426 error), so I've gone back to 4.3 RC3. Now there is a 4.3 branch available for the Godot submodule so I've rebuilt the plugin libraries and the export now works.

When running on my phone from Godot, the Game Center authenticate call did nothing but there were no obvious console errors. I opened the Xcode project file and ran my app from there and the following error appeared in the Xcode console:

`Could not load services for GameKit. This likely means your game is missing the com.apple.developer.game-center entitlement...`

Click on the Signing & Capabilities tab, then +Capability and double click on "Game Center" to create a new entitlements file. This fixed the Game Center authenticate call for me but I'm getting a not yet live message when I try and view my leaderboard. Hope this helps.

**Comment by owlnewworlds** [comment]
> Ok, so uploading a 4.2.2 build to TestFlight doesn't work (ITMS-90426 error), so I've gone back to 4.3 RC3. Now there is a 4.3 branch available for the Godot submodule so I've rebuilt the plugin libraries and the export now works.
> 
> When running on my phone from Godot, the Game Center authenticate call did nothing but there were no obvious console errors. I opened the Xcode project file and ran my app from there and the following error appeared in the Xcode console:
> 
> `Could not load services for GameKit. This likely means your game is missing the com.apple.developer.game-center entitlement...`
> 
> Click on the Signing & Capabilities tab, then +Capability and double click on "Game Center" to create a new entitlements file. This fixed the Game Center authenticate call for me but I'm getting a not yet live message when I try and view my leaderboard. Hope this helps.

Yes it works like that. And if you try a post_score call you will see its working too despite the not live yet warnings ^^

**Comment by RocketRonz** [comment]
I pretty much followed these guides but checked out the Godot 4.3 branch when building the plugin:

[https://www.peanuts-code.com/en/tutorials/gd0021_game_center_plugin/](url)
[https://www.peanuts-code.com/en/tutorials/gd0022_implement_game_center/](url)

- Run the iOS export from Godot to generate the .ipa file (I could only get this working with "Export With Debug" checked)
- When the export completes, there should be a .xcodeproj file in the releases folder, open this in Xcode.
- Click on the Signing & Capabilities tab, then +Capability and double click on "Game Center" to create a new entitlements file.
- You should be able to run the app on a connected device via Xcode and use the Game Center plugin functionality.

It's a bit convoluted but does the job. Would be great to run directly from Godot but I couldn't get the plugin to work without manually adding it in Xcode. Hope this helps.

**Comment by Beebster-UK** [comment]
@RocketRonz Thanks for validating my steps so far, I stumbled on all the above and successfully generated the plugin and debug exported the iOS project with GameCenter checked. I've added the gamecenter capability in Xcode and published to Test Flight no problem . I can see from the Xcode debug logs that GameCenter plugin does exists but attempts at authentication returns a '0' which doesn't seem right. Equally I'm unable to post a score.

Feel so close and would love to get this working, any ideas.

**Comment by RocketRonz** [comment]
If I remember correctly it took a while for my leaderboard to start working when I first made it available. A return value of 0 is the OK response, so the "Welcome back" popup should appear when you call authenticate. Post score should also return 0 if successful.  Might be useful to look at the Objective-C code for the plugin:

https://github.com/godot-sdk-integrations/godot-ios-plugins/blob/master/plugins/gamecenter/game_center.mm

The constant values are included in the Godot _CoreConstant struct (OK is at line 588):

https://github.com/godotengine/godot/blob/4.3/core/core_constants.cpp

**Comment by Beebster-UK** [comment]
Thanks for swift reply and confirming response of 0 is 'Okay' really helpful.

Thankfully I do get the welcome screen so should have realised, I thought that might have been simply because the entitlement was set so was unsure. The Godot docs also threw me off as it showed successful auth as : -

`{
  "type": "authentication",
  "result": "ok",
  "player_id": the value from GKLocalPlayer::playerID,
}`

Is the Leaderboard available to post to even if I've only submitted to TestFlight or does it require full submission to the App store?

**Comment by RocketRonz** [comment]
Actually, looking at the plugin code. The authenticate and post methods return OK when that method has successfully called the equivalent Game Center code. This call is asynchronous so the actual result from Game Center is placed in an event queue. You need to use "get_pending_event_count" and "pop_pending_event" to see what Game Center responded with.

Leaderboards & achievements should be available on TestFlight as they need to be tested before full submission to the App Store. Have you tried calling "show_game_center" on the plugin to see if it displays the leaderboard?

**Comment by Beebster-UK** [comment]
I have called "show_game_center" and that does indeed trigger entry to the leaderboard but sadly score remains '0' points despite numerous scores having been posted. Leadboard status is 'Not Live' but assuming that relates to publishing to store?

**Comment by RocketRonz** [comment]
I'm pretty sure I was posting scores to my leaderboard on TestFlight when it had the "Not Live" status and seem to remember having a similar problem where they didn't appear for possibly more than a day. Then it just started working.

Maybe try signing out your Game Center account on the phone. The sign in popup should appear instead of the welcome popup when you call authenticate from your game. You could also select "Delete Test Data" from the leaderboards screen in App Store Connect to see if that kicks it into action.

**Comment by Beebster-UK** [comment]
Success!!  Created a new leaderboard with simpler ref name and id of "highscore" and posted to that and results have now posted.

Massive thanks for your help really appreciated it!

**Comment by RocketRonz** [comment]
No worries. Well done for not giving up, I know how frustrating this stuff can be. All the best with your game.

**Comment by Beebster-UK** [comment]
Thank you, it's retro horizontal shooter not exactly great choice for iOS touch screen. Managed also to get iCloud key pair storage working based on experience above which I'll likely just use for maintaining high score between devices.

Enjoying Rock Hopper nice work! Very slick.

**Comment by RocketRonz** [comment]
Thanks very much, I've not had a huge number of downloads but hopefully get there in the end.

It's good to see other devs using Godot for mobile games as they seem very focused on Steam. Not sure what the performance on mobile is like with 3D but it's certainly good enough to create high quality 2D games, which are much more fun IMO
